<a href="https://colab.research.google.com/github/aliroshandel98/Pytorch/blob/main/00_PytorchFundamentalsExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hello Everybody
Im Ali and here im gonna share my exercises and experiences during learning deep learning with pytorch.
this is first exercise notebook of me and all of the content that ive learned is from here: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [1]:

# Import Usable Libraries

import torch
import numpy as np

**1.Create a random tensor with shape (7, 7).**

In [2]:
tensor = torch.rand(7, 7)
tensor

tensor([[0.0804, 0.1550, 0.5129, 0.1567, 0.4128, 0.6079, 0.0712],
        [0.8650, 0.2012, 0.5213, 0.6805, 0.6825, 0.8083, 0.9313],
        [0.3914, 0.1759, 0.9026, 0.5126, 0.1582, 0.9489, 0.7089],
        [0.1033, 0.6346, 0.1153, 0.7891, 0.3426, 0.5822, 0.2281],
        [0.6123, 0.9929, 0.5133, 0.2471, 0.1800, 0.2952, 0.1220],
        [0.7882, 0.1787, 0.3025, 0.8482, 0.7875, 0.9275, 0.2792],
        [0.5851, 0.9549, 0.4100, 0.9240, 0.5945, 0.8249, 0.7714]])

**2.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).**


In [3]:
matmul = torch.matmul(tensor, torch.rand(1, 7).T)
matmul

tensor([[1.1132],
        [1.9525],
        [1.7204],
        [1.2424],
        [1.3284],
        [1.9405],
        [2.1078]])

**3.Set the random seed to 0 and do exercises 2 & 3 over again.**

In [4]:
Random_Seed = 0
torch.manual_seed(Random_Seed)
tensor = torch.rand(7, 7)
torch.manual_seed(Random_Seed)
matmul = torch.matmul(tensor, torch.rand(1, 7).T)
print(f"tensor(7, 7) is:\n {tensor}")
print(f"matmul is:\n {matmul}")



tensor(7, 7) is:
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
matmul is:
 tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


**4.Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.**

In [17]:
random_seed = 1234
if torch.cuda.is_available():
  torch.cuda.manual_seed(random_seed)
  print("cuda is OK")
else:
  torch.manual_seed(random_seed)
  print("cuda isnt OK")

tensor = torch.rand(10, 10).to('cuda')
tensor.device


cuda is OK


device(type='cpu')

**5.Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).**

In [18]:
torch.manual_seed(1234)
random_tensor_one = torch.rand(2,3).to('cuda')
torch.manual_seed(1234)
random_tensor_two = torch.rand(2,3).to('cuda')
random_tensor_one == random_tensor_two

tensor([[True, True, True],
        [True, True, True]], device='cuda:0')

**6.Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).**

In [19]:
matmul = torch.matmul(random_tensor_one, random_tensor_two.T)
matmul

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

**7.Find the maximum and minimum values of the output of 6.**

In [20]:
print(f"max is: {torch.max(matmul)}")
print(f"min is: {torch.min(matmul)}")

max is: 0.628727912902832
min is: 0.21611443161964417


**8.Find the maximum and minimum index values of the output of 6.**

In [21]:
print(f"max is: {torch.argmax(matmul)}")
print(f"min is: {torch.argmin(matmul)}")

max is: 3
min is: 1


**9.Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

In [25]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
tensor_squeezed = torch.squeeze(tensor)
print(f"the first tensor is:\n {tensor} \n and its shape is:\n {tensor.shape}")
print(f"the second tensor is:\n {tensor_squeezed} \n and its shape is:\n {tensor_squeezed.shape}")

the first tensor is:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
 and its shape is:
 torch.Size([1, 1, 1, 10])
the second tensor is:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) 
 and its shape is:
 torch.Size([10])


And its all done (:
Wish you all best.